# This is a basic workflow to help you get started with Actions

name: PR

on:
  pull_request:
    branches: [ master ]

# This is a basic workflow to help you get started with Actions

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.9.0 # optional
          token: ${{ github.token }}

      - run: npm install

      # Test
      - run: npm run test
      - run: npm run build
